FROM node:20-slim

RUN npm config set registry https://registry.npmmirror.com

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--config", "vite.config.docker.js"]
