"""add progress and logs fields

Revision ID: 20260523_add_progress_logs
Revises: f1c1ec0125fe
Create Date: 2026-05-23

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260523_add_progress_logs'
down_revision: Union[str, None] = 'f1c1ec0125fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_results', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('validation_results', sa.Column('logs', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_results', 'logs')
    op.drop_column('validation_results', 'progress')
    # ### end Alembic commands ###
