"""initial schema

Revision ID: f1c1ec0125fe
Revises: 
Create Date: 2026-05-23 07:17:11.544609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c1ec0125fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builtin_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expectation_type', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('parameters_schema', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expectation_type')
    )
    op.create_table('datasources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('db_type', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=True),
    sa.Column('builtin_rule_id', sa.UUID(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('mostly', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('row_condition', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builtin_rule_id'], ['builtin_rules.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_expectations', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('result_detail', sa.JSON(), nullable=False),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['validation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_table('validation_tasks')
    op.drop_table('validation_rules')
    op.drop_table('datasources')
    op.drop_table('builtin_rules')
    # ### end Alembic commands ###
